### ISSUE TITLE
localStorage is not defined (but defined???)

### ISSUE THREAD

**Issue by grendizeras** [NathanaelA/nativescript-localstorage#15]
I am experiencing weird behaviour:
when calling localStorage.setCurrent("key","value") I get **localStorage is not defined** when running on android, but when debugging, it is not undefined. I mean debugging watch shows that localStorage is set, but when stepping over, it throws exception.
I'm using tns version 4.1.0. Application is Nativescript+Angular.

Code:
`import * as localstorage from 'nativescript-localstorage';`

Error:
```

ReferenceError: localStorage is not defined
    at Function.Utils.setToken (file:///data/data/org.nativescript.betobe/files/app/utils/utils.js:18:9)
    at MapSubscriber.project (file:///data/data/org.nativescript.betobe/files/app/services/authorization.service.js:24:31)
    at MapSubscriber._next (file:///data/data/org.nativescript.betobe/files/app/tns_modules/rxjs/internal/operators/map.js:86:35)
    at MapSubscriber.Subscriber.next (file:///data/data/org.nativescript.betobe/files/app/tns_modules/rxjs/internal/Subscriber.js:103:18)
    at onLoad (file:///data/data/org.nativescript.betobe/files/app/tns_modules/@angular/http/bundles/http.umd.js:1404:38)
    at file:///data/data/org.nativescript.betobe/files/app/tns_modules/tns-core-modules/xhr/xhr.js:151:21
    at Array.forEach (<anonymous>)
    at XMLHttpRequest.emitEvent (file:///data/data/org.nativescript.betobe/files/app/tns_modules/tns-core-modules/xhr/xhr.js:150:18)
    at XMLHttpRequest._setReadyState (file:///data/data/org.nativescript.betobe/files/app/tns_modules/tns-core-modules/xhr/xhr.js:224:22)
    at XMLHttpRequest._loadResponse (file:///data/data/org.nativescript.betobe/files/app/tns_modules/tns-core-modules/xhr/xhr.js:93:14)
    at file:///data/data/org.nativescript.betobe/files/app/tns_modules/tns-core-modules/xhr/xhr.js:70:27
    at ZoneDelegate.invoke (file:///data/data/org.nativescript.betobe/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:388:26)
    at Object.onInvoke (file:///data/data/org.nativescript.betobe/files/app/tns_modules/@angular/core/bundles/core.umd.js:4146:33)
    at ZoneDelegate.invoke (file:///data/data/org.nativescript.betobe/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:387:32)
    at Zone.run (file:///data/data/org.nativescript.betobe/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:43)
```

**Comment by NathanaelA** [comment]
Have you tried:
- Deinstall app from Android device/emulator
- tns platform clean android
- tns run android

**Comment by grendizeras** [comment]
Yes I have. With no luck.

**Comment by grendizeras** [comment]
I am about to give up, nothing fixes the issue. @NathanaelA  do you have any ideas? Or should I switch to other plugins?

**Comment by NathanaelA** [comment]
@grendizeras -- without a sample of what you are doing; I'm not sure why it isn't working for you.    I just updated the demo to use NS 4.1 and it still works fine w/o any changes.

**Comment by grendizeras** [comment]
@NathanaelA  It is fixed now. I'm not sure what fixed it, I guess it was your update, because the issue wasn't only on my PC, but on my colleague's PC also. Anyways, thank you!
